check condor installation

diff --git a/metadata/csv2htc.yaml.j2 b/metadata/csv2htc.yaml.j2
--- a/metadata/csv2htc.yaml.j2
+++ b/metadata/csv2htc.yaml.j2
@@ -2,10 +2,23 @@ merge_type: 'list(append)+dict(recurse_array)+str()'
 write_files:
 -   content: |
         #!/bin/bash
-        M=$((cd /var/log/condor;awk '/Error/{split($0,W,"Error");print W[2]}/ERROR/{split($0,W,"ERROR");print W[2]}' MasterLog StartLog)|tr ":" " "|awk 'NF>2{print "/"$1"_"$2"_"$3}'|sort -u|tr -d '\n')
-        if [ "X${M}" != 'X' ]; then
-          curl https://{{cs_condor_host}}/$(hostname -s)/STARTD${M}
-        fi
+        function T () 
+        {
+         touch $K$1
+         S=$(cat $K$1)
+         wc -l <$I$1>$K$1
+         tail -n +$((S+1)) $I$1
+        }   
+            
+         which condor_master &>/dev/null||(curl https://{{cs_condor_host}}/$(hostname -s)/STARTD/HTCondor_is_not_installed && exit)
+
+         I=/var/log/condor/
+         K=/tmp/csv2htc.K.
+         O="$(T MasterLog)"
+         O="$O""$(T StartLog)"
+         
+        M=$(echo "${O}"|awk '/Error/{split($0,W,"Error");print W[2]}/ERROR/{split($0,W,"ERROR");print W[2]}'|tr ":" " "|awk 'NF>2{print "/"$1"_"$2"_"$3}'|sort -u|tr -d '\n')
+        if [ "$M" != "" ];then while true; do curl https://{{cs_condor_host}}/$(hostname -s)/STARTD${M} && break;sleep 30;done;fi
     owner: root:root
     permissions: 0700
     path: /root/csv2HTC
